Add collision sounds
Code-Coffee-Jams/BrickGame pull request #6
Opened 2022-06-12 19:46 UTC by Nieminik

2022-06-21 17:09 UTC, Yamsha75 requested changes

2022-06-21 17:09 UTC, Yamsha75 commented on collisions.lua
> +local collision_types = { Wall = 1, Brick = 2, Paddle = 3}
Please make it more consistent with similar enums found in main.lua. Also, in general please use **camelCase** and **UpperCamelCase** for "classes" (such as enums).

2022-06-21 17:09 UTC, Yamsha75 commented on collisions.lua
> +local function calculateBallEdgesCollision(ball, newBallPosition, edges, collision_type)
camelCase

2022-06-21 17:09 UTC, Yamsha75 commented on main.lua
> +    hit_sound = love.audio.newSource("assets/sounds/soft-bang.ogg", "static")
camelCase

2022-06-21 17:09 UTC, Yamsha75 commented on collisions.lua
> +module.collision_types = collision_types
Maybe name it "TypeEnum" or "Type", so that outside (in main) it would be called `Collisions.TypeEnum.XXX`

2022-06-21 17:09 UTC, Yamsha75 commented on main.lua
> +    if collision_type == Collisions.collision_types.Wall then
How about moving this part to inside `else` in line 250?

2022-06-21 17:09 UTC, Yamsha75 commented on main.lua
> +local wall_sound_2 = love.audio.newSource("assets/sounds/metal.wav", "static") -- in case one wall sound is played during second collision
How about moving initialization to `love.load`? Also, camelCase

2022-06-24 17:04 UTC, Nieminik commented
Sorry about all the snakes I wanted to include in the code ; D

2022-06-24 18:03 UTC, Yamsha75 approved these changes

2022-06-24 18:44 UTC, merged